torch_compile: false
output_classes: 9 
fps: 4
batch_size: 2
image_size: [128, 128]
dataset_dir: pokeagent/emulator_v1  
s3_bucket: b4schnei    
epochs: 10
lr: 1.0e-4
wandb_project: "pokeagent"
output_path: "./checkpoints"