torch_compile: false
output_classes: 10 
fps: 4
batch_size: 1
image_size: [128, 128]
dataset_dir: pokeagent/emulator_v1  
s3_bucket: b4schnei    
epochs: 10
lr: 3.0e-4
weight_decay: 0.01
wandb_project: "pokeagent"
output_path: "./checkpoints"