torch_compile: false
output_classes: 10 
fps: 20
batch_size: 2
image_size: [128, 128]
dataset_dir: pokeagent/emulator_v1  
s3_bucket: b4schnei    
epochs: 10
lr: 5.0e-5
weight_decay: 0.001
wandb_project: "pokeagent"
output_path: "./checkpoints"
activation_checkpoint: true