output_classes: 9
fps: 4
batch_size: 1
image_size: [128, 128]
dataset_dir: pokeagent/rnd_policy
validation_dir: pokeagent/val
s3_bucket: b4schnei    
epochs: 1
lr: 3.0e-4
weight_decay: 0
wandb_project: "pokeagent"
output_path: "./checkpoints/idm_model.pt"
torch_compile: false
