architecture: "vpt"
idm_path: ".cache/pokeagent/online/0c26fd45-e777-4ca6-a8c5-01861c1b0260_pk3/checkpoints/checkpoint-60224/idm_model.safetensors"
output_dir: ".cache/pokeagent/checkpoints_test"
num_train_epochs: 10
per_device_train_batch_size: 4
save_strategy: "epoch"
save_total_limit: 10
learning_rate: 5.0e-5
weight_decay: 0.00001
adam_beta2: 0.95
warmup_ratio: 0.05
lr_scheduler_type: "linear"
logging_steps: 1
gradient_checkpointing: false
report_to: "wandb"
eval_strategy: "steps"
eval_steps: 0.1
dataloader_num_workers: 8
data_path: ".cache/pokeagent/intervals_padded.json"
