architecture: "vpt"
idm_path: ".cache/pokeagent/rnd_idm_model.pt"
load_path: checkpoints/vpt_early_game/f0f07753c1b89391497387fe7b36aa6d1a8304a2/checkpoint-7400/model.safetensors
output_dir: ".cache/pokeagent/online"

# unused by VPT rollout but required by HfArgumentParser
num_train_epochs: 1
per_device_train_batch_size: 1
save_strategy: "no"
report_to: "wandb"

# inference
inference_architecture: "vpt"
online: true
agent_steps: 57600 # 14400 = 1 hour
save_state: .cache/pokeagent/save_state/truck_start.state
rom_path: .cache/pokeagent/rom/rom.gba
sampling_strategy: "temperature"
temperature: 1.0
context_length: 64
actions_per_second: 4
agent_fps: 2

# unused IDM args (required by parser)
output_classes: 9
idm_fps: 4
idm_batch_size: 2
idm_image_size: [128, 128]
idm_epochs: 1
idm_lr: 5.0e-5
idm_weight_decay: 0
idm_max_grad_norm: 1.0
wandb_project: pokeagent
idm_gradient_accumulation_steps: 1
idm_output_path: rnd_idm_model.pt
idm_dataloaders_per_device: 1
